name: Hyperexecute-Playwright
on:
  schedule:
    - cron: '30 5,17 * * *'
  
jobs:
  run-commands:
    runs-on: ubuntu-latest
     steps:
      - name: Check out repo code
        uses: actions/checkout@v4  # Downloads your repository code onto the runner

      - name: Run a shell command
        run: echo "Hello World! Your YAML file is running." # Executes standard shell scripts
